name: create_env

on:
    - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: create_env # email-from-python.py
        env:
          TIINGO_API: ${{ secrets.TIINGO_API }}
          TIINGO_ENDPOINT: ${{ secrets.TIINGO_ENDPOINT }}
        run: echo -e "TIINGO_API=$TIINGO_API\nTIINGO_ENDPOINT=$TIINGO_ENDPOINT" > .env